### ISSUE TITLE
cannot target nested elements by vudufied classname

### ISSUE THREAD

**Issue by sepowitz** [dhunninghake/vudu#16]

**Comment by hhff** [comment]
@sepowitz can u provide an example?

**Comment by sepowitz** [comment]
```
<div class=styles.vuduClass>
    <img  class=styles.image src=... />
</div>

const styles = v({
   vuduClass: {
      ...,
      ':hover': {
        image: {
           ...do stuff
          }
       }
   },
   image: {
    ...
  }
})
```

**Comment by dhunninghake** [comment]
Yo @sepowitz ! This is a tricky one. What about defining the image separately?
```js
const imgStyles = v({
  img: {
    ...
  }
});

const styles = v({
  vuduClass: {
    ...,
    ':hover': {
      [`.${imgStyles.img}`]: {
         ...
      }
    }
  }
})
```
then:
```html
<div class=styles.vuduClass>
  <img class=imgStyles.img src=... />
</div>
```

Not super ideal, but also not terrible. Wdyt? Also is this still an issue?
cc: @hhff

**Comment by hhff** [comment]
I like the solution above tho!  We should add it to the README?

I feel like there's always going to be a tendency to try and nest selectors in the same way they're nested in the DOM.  Thats a natural behavior coming from classic SCSS etc

Potentially we could do something like this:
```
<div class={styles.vuduClass.default}>
  <img class={styles.vuduClass.image} src=... />
</div>
```

if a class nests another class, the vudu output could be
```
{
  vuduClass: {
    default: "vuduClass-default-12jf38"
    image: "vuduClass-image-249jf"
  }
}
```

But I don't really love it.  Just thinking out loud.
