### ISSUE TITLE
Vudu de-camelizes selectors within their sub-selector

### ISSUE THREAD

**Issue by hhff** [dhunninghake/vudu#17]
```
'input[name="user[handleName]"': {
  background: 'wheat'
}
```

is rendered in vudu as:
```
'input[name="user[handle-name]"': {
  background: 'wheat'
}
```
This was unexpected - I'd guess that text within a `[]` selector would not be camelized

**Comment by dhunninghake** [comment]
@hhff Got a fix for this in the Vudu updates PR! https://github.com/dhunninghake/vudu/pull/19
